"""Initial migration

Revision ID: 3f08bf010cce
Revises: 
Create Date: 2026-01-17 14:22:39.564914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f08bf010cce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_uuid', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('strategy_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('final_capital', sa.Float(), nullable=True),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('falsification_triggered', sa.Boolean(), nullable=True),
    sa.Column('falsification_reason', sa.String(), nullable=True),
    sa.Column('trades_json', sa.JSON(), nullable=True),
    sa.Column('equity_curve_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_id'), 'simulation_results', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_results_simulation_uuid'), 'simulation_results', ['simulation_uuid'], unique=False)
    op.create_index(op.f('ix_simulation_results_ticker'), 'simulation_results', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_results_ticker'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_simulation_uuid'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
